export const Paths = {
    Login: "/login",
    Dashboard: "/dashboard",
    Products: "/products",
    Outlets: "/outlets",
    Partners: "/partners",
    Inventory: "/inventory",
    Transactions: "/transactions",
    Units: "/units",
    Settings: "/settings",
    EditPartner: "/edit-partner",
    AddPartner: "add-partner",
    AddTransaction: "add-transaction",
    EditTransaction: "/edit-transaction",
}